---
- name: get server facts retries "{{ retrytimes }}" times delay "{{ delaytime }}" sec until got VERIRY_RESIZE
  local_action:
    module: rax_facts
    credentials: ~/.raxpub
    id: "{{ server_id }}"
    region: "{{ region }}"
  register: serverfacts
  until: serverfacts.ansible_facts.status == "VERIFY_RESIZE"
  retries: "{{ retrytimes }}"
  delay: "{{ delaytime }}"
  ignore_errors: false

- name: debug
  debug: var=serverfacts.ansible_facts.status
