---
- name: get server facts retries 15 times delay 30 sec until got VERIRY_RESIZE
  local_action:
    module: rax_facts
    credentials: ~/.raxpub
    id: "{{ server_id }}"
    region: "{{ region }}"
  register: serverfacts
  until: serverfacts.ansible_facts.status == "VERIFY_RESIZE"
  retries: 15
  delay: 30
  ignore_errors: false

- name: debug
  debug: var=serverfacts.ansible_facts.status
