---
- hosts: localhost
  connection: local
  gather_facts: true
  vars: 
    names: "{{ lookup('file', '~/data/servernames.txt') }}"
    servernames: "{{ names.split(\"\n\") }}"
    deletetime: "{{ ansible_date_time[\"iso8601\"] }}"
  roles:
     - deltestservers

