---  
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    contents: "{{ lookup('file', '~/data/serverid.txt') }}"
    servers: "{{ contents.split(\"\n\") }}"
  roles:
    - getservers

