---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    ids: "{{ lookup('file', '~/data/serverid.txt') }}"
    servers: "{{ ids.split(\"\n\") }}"
    server_id: "{{ servers[0] }}"
  roles:
#     - handlers
     - confirmstatus
     - getservers
