---
- hosts: localhost
  connection: local
  gather_facts: true
  vars: 
    ids: "{{ lookup('file', '~/data/serverid.txt') }}"
    servers: "{{ ids.split(\"\n\") }}"
  roles:
     - resizetestservers
     - getservers
