---
- hosts: localhost
  connection: local
  gather_facts: true
  vars: 
    contents: "{{ lookup('file', '~/data/serverid.txt') }}"
    contentlinks: "{{ lookup('file', '~/data/linkserver.txt') }}"
  roles:
     - resizetestservers

