---
- name: Test Server build requests
  local_action:    
    module: rax
    credentials: ~/.raxpub
    name: "{{ prefix }}-testserver%02d"
    flavor: "{{ flavor2 }}"
    image: "{{ image }}"
    files: "{{ files }}"
    region: "{{ region }}"
    state: present
    count: 2
    count_offset: 1
    exact_count: yes
    group: "{{ prefix }}-test_sox"
    wait: yes
    wait_timeout: 3000
  register: testcs
  tags:
    - sox

- name: delete serverid.txt to create new one
  local_action: 
    module: file
    path: ~/data/serverid.txt
    state: absent

- name: save server id to file
  local_action: 
    module: lineinfile
    create: yes
    dest: ~/data/serverid.txt
    line: "{{ item.id}}"
  with_items: testcs.success
  when: testcs.action == 'create'

- name: delete servernames.txt to create new one
  local_action:
    module: file
    path: ~/data/servernames.txt
    state: absent

- name: save server name to file
  local_action:
    module: lineinfile
    create: yes
    dest: ~/data/servernames.txt
    line: "{{ item.name }}"
  with_items: testcs.success
  when: testcs.action == 'create'

- name: gather info about server write to files (account, servername, serverid, flavor, created, updated, status)
  local_action:
    module: lineinfile
    create: yes
    dest: ~/sox/data/serversinfo.csv
    insertafter: EOF
    line: "{{ item.rax_tenant_id }}, {{ item.rax_name }}, {{ item.id }}, {{ item.rax_flavor[\"id\"] }}, {{ item.rax_created }}, {{ item.rax_updated }}, {{ item.rax_status }}"
  with_items: testcs.success
  when: testcs.action == 'create'
 
