---
- name: check delete time
  debug: var=deletetime

- name: Test Server delete requests
  local_action:    
    module: rax
    credentials: ~/.raxpub
    name: "{{ item }}"
    flavor: "{{ flavor }}"
    image: "{{ image }}"
    region: "{{ region }}"
    state: absent
    group: "{{ prefix }}-test_sox"
    wait: yes
    wait_timeout: 1200
  with_items: "{{ servernames }}"
  register: del_testcs

#- name: check delete results
#  debug: var=del_testcs.results

- name: gather info about server write to files (account, servername, serverid, flavor, created, updated (~deletetime), status)
  local_action:
    module: lineinfile
    create: yes
    dest: ~/sox/data/{{ resultfile }}
    insertafter: EOF
    line: "{{ item.success[0].rax_tenant_id }}, {{ item.success[0].name }}, {{ item.success[0].id }}, {{ item.success[0].rax_flavor[\"id\"] }}, {{ item.success[0].rax_created }}, {{ item.success[0].rax_updated }}, {{ item.success[0].rax_status }}, {{ item.action }}"
  with_items: del_testcs.results
