- name: Test Server delete requests
  local_action:    
    module: rax
    credentials: ~/.raxpub
    name: "{{ prefix }}-testserver%02d"
    flavor: performance1-1
    image: "{{ image }}"
    region: "{{ region }}"
    state: absent
    count: 5
    count_offset: 1
    exact_count: yes
    group: "{{ prefix }}-test_sox"
    wait: yes
    wait_timeout: 1200
  register: del_testcs

- name: gather info about server write to files (account, servername, serverid, flavor, created, updated, status)
  local_action:
    module: lineinfile
    create: yes
    dest: ~/sox/data/serversinfo.csv
    insertafter: EOF
    line: "{{ item.rax_tenant_id }}, {{ item.rax_name }}, {{ item.id }}, {{ item.rax_flavor[\"id\"] }}, {{ item.rax_created }}, {{ item.rax_updated }}, {{ item.rax_status }}"
  with_items: del_testcs.success
  when: del_testcs.action == 'delete'

#- name: gather info about servers
#  set_fact:
#    name: "{{ item.name }}"
#    id: "{{ item.id }}"
#    flavor: "{{ item.rax_flavor[\"id\"]}}"
#    servername: "{{ item.rax_name }}"
#    created: "{{ item.rax_created }}"
#    updated: "{{ item.rax_updated }}"
#    group: "server_info"
#  with_items: del_testcs.success
#  when: del_testcs.action == 'delete'
